### ISSUE TITLE
GetResponseのerrorLog

### ISSUE THREAD

**Issue by hsgw-yuta** [bolg-developers/chat#10]
`04-17 15:42:34.126 21002-21002/com.example.chat_android_test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.chat_android_test, PID: 21002
    io.grpc.StatusRuntimeException: UNAVAILABLE
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:210)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:191)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:124)
        at io.grpc.examples.helloworld.HelloServiceGrpc$HelloServiceBlockingStub.getHello(HelloServiceGrpc.java:138)
        at com.example.caht.MainActivity$onCreate$1.onClick(MainActivity.kt:51)
`

**Comment by hsgw-yuta** [comment]
kotlinのコード
`class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        /* チャンネル設定 */
        val channel : ManagedChannel = ManagedChannelBuilder
            .forAddress("127.0.0.1", 50051)
            .usePlaintext(true)
            .build()
        /* スタブ設定
         * ※今回は簡易のためnewBlockingStubを使用する
         */
        val stub : HelloServiceGrpc.HelloServiceBlockingStub = HelloServiceGrpc.newBlockingStub(channel)
        //val asyncStub = HelloServiceGrpc.newStub(channel)
        /* リクエスト設定 */
        val request: Empty = Empty.newBuilder().build()
        /* 受信テキスト */
        val res_text: TextView = findViewById(R.id.response_text) as TextView
        /* リクエストボタン */
        val button: Button = findViewById(R.id.request_btn) as Button
        button.setOnClickListener(object : View.OnClickListener {
            override fun onClick(v: View?) {
                var resmsg :String? = null
                /* 実行 */
                /*val res: GetHelloRes = stub.getHello(request)
                res_text.setText(res.msg)*/

                    try {
                        resmsg = stub.getHello(request).msg
                    }catch (e: Exception){
                        resmsg = e.toString()
                        Log.d("getmessage","来てない")
                    }finally {
                        res_text.setText(resmsg)
                    }
            }
        })
    }

**Comment by 0g3** [comment]
ん？　これHelloServiceのほうだね
それ下のリポジトリで管理してるので、お手数ですがそっちでほうでissue出してほしいです！
https://github.com/bolg-developers/sgrpc
